import { useRef } from 'react'
import useInView from '../hooks/useInView'
import BrochuresGrid from './BrochuresGrid'
import TitleHeader from './TitleHeader'
import ScrollDownPrompt from './ScrollDownPrompt'
import SectionIndex from './SectionIndex'

const BROCHURES_NOTE =
  'These brochures are generated by AI — simple, step-by-step guides that explain how each piece of furniture can be built using the simplest materials, such as brick, wood pallets, and fabric, so that anyone in the community can use them to build the elements themselves.'

export default function BrochuresSection({ innerRef, onNext, onBack, n }) {
  const ref = useRef(null)
  const attachRef = el => { ref.current = el; innerRef?.(el) }
  const inView = useInView(ref)

  return (
    <section ref={attachRef} className="snap-section" style={{ display: 'flex', flexDirection: 'column', background: '#fff' }}>
      <TitleHeader title="Brochures" active={inView} />
      <div style={{ position: 'relative', flex: '1 1 auto', minHeight: 0, overflow: 'hidden', display: 'flex', flexDirection: 'column' }}>
        <p style={{
          flexShrink: 0, margin: '1.5rem 0 0', textAlign: 'center',
          fontFamily: "'BBTorsosPro', sans-serif",
          fontSize: '0.7rem', letterSpacing: '0.15em', textTransform: 'uppercase',
          color: '#8A8A8A',
        }}>
          Tap a brochure to view the full document
        </p>

        <BrochuresGrid />

        <p style={{
          flexShrink: 0, margin: 0, padding: '0 4rem 6.5rem',
          textAlign: 'center', maxWidth: '760px', alignSelf: 'center',
          fontFamily: "'BBTorsosPro', sans-serif",
          fontSize: '0.9rem', lineHeight: 1.6,
          color: '#555',
        }}>
          {BROCHURES_NOTE}
        </p>

        {n && <SectionIndex n={n} />}
        {onBack && <ScrollDownPrompt visible={inView} onClick={onBack} label="Back" icon="↑" position="top" />}
      </div>
      <ScrollDownPrompt visible={inView} onClick={onNext} />
    </section>
  )
}
